### PR TITLE
fix(chaos): generate correct loops from AST

### PR DESCRIPTION
**Pull request by alexbatashev**
First block in region can't have predecessors. Generate MLIR Loop
dialect for loops from AST and drop ForOp from clang dialect.

### CODE REVIEW

**Comment by alexbatashev** [comment]
@AlexeySotkin here's a fixed version of IR https://gist.github.com/alexbatashev/dfc05262bac2fdb3669293382647d7b3

It now generates correct loops, but the terminator is missing from the sgemm function.

**Comment by AlexeySotkin** [comment]
> It now generates correct loops, but the terminator is missing from the sgemm function.

If I remove ` -> none ` from the second line of [test_v2.mlir](https://gist.github.com/alexbatashev/dfc05262bac2fdb3669293382647d7b3#file-test_v2-mlir), add `return` at the end of the sgemm function and comment out the main function, I can produce llvm ir from it with the following command:
`mlir-opt --convert-std-to-llvm test_v2.mlir | mlir-translate --mlir-to-llvmir` 

There is a problem with `%3 = "std.alloc"(%2) {alignment = 4 : i64} : (i32) -> f32` line.

Also I see type mismatch between sgemm arguments and what is passed to `std.call` : `%arg0: memref<?xf32>` vs `f32`

**Comment by alexbatashev** [comment]
> > It now generates correct loops, but the terminator is missing from the sgemm function.
> 
> If I remove `-> none` from the second line of [test_v2.mlir](https://gist.github.com/alexbatashev/dfc05262bac2fdb3669293382647d7b3#file-test_v2-mlir), add `return` at the end of the sgemm function and comment out the main function, I can produce llvm ir from it with the following command:
> `mlir-opt --convert-std-to-llvm test_v2.mlir | mlir-translate --mlir-to-llvmir`

It looks like MLIR's `None` type is not the same as C++'s `void`, which is a little problematic. BTW, did you use top of the trunk llvm? Does it convert `memref`s to pointers? Or structures instead?

> 
> There is a problem with `%3 = "std.alloc"(%2) {alignment = 4 : i64} : (i32) -> f32` line.
> 
> Also I see type mismatch between sgemm arguments and what is passed to `std.call` : `%arg0: memref<?xf32>` vs `f32`

Hm... `CXXNewExpr` seems to be returning be a type of a *single* array element. I need to convert it to `memref`, though.

**Comment by alexbatashev** [comment]
@AlexeySotkin good news: it compiles. Bad news: it crashes

```
aleksandrbatasev@MacBook-Pro-Aleksandr ~/P/w/l/build> lldb ./a.out
(lldb) target create "./a.out"
Current executable set to './a.out' (x86_64).
(lldb) r
Process 28653 launched: '/Users/aleksandrbatasev/Projects/work/llvm-project/build/a.out' (x86_64)
Process 28653 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x7ffeecbff708)
    frame #0: 0x0000000100000f9e a.out`main + 174
a.out`main:
->  0x100000f9e <+174>: callq  0x100000cf0               ; sgemm(float const*, float const*, float*, int, int, int)
    0x100000fa3 <+179>: xorl   %eax, %eax
    0x100000fa5 <+181>: movq   %rbp, %rsp
    0x100000fa8 <+184>: popq   %rbp
Target 0: (a.out) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x7ffeecbff708)
  * frame #0: 0x0000000100000f9e a.out`main + 174
    frame #1: 0x00007fff641037fd libdyld.dylib`start + 1
    frame #2: 0x00007fff641037fd libdyld.dylib`start + 1
```

Default MLIR->LLVM conversion uses way too strange calling conventions. I bet that's the problem.

**Pull request merged**
